{exec} = require 'child_process'
task 'build', 'Build project from src/*.coffee to lib/*.js', ->
  exec 'browserify -t coffeeify ./main.coffee > ../js/lib/main.js', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr